pr: none
trigger:
- try

variables:
- group: prod-credentials

jobs:
- job: Linux
  timeoutInMinutes: 600
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: steps/run.yml
  strategy:
    matrix:
      dist-x86_64-linux: {}
- job: Windows
  timeoutInMinutes: 600
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: steps/run.yml
  strategy:
    matrix:
      dist-x86_64-mingw:
        SCRIPT: python x.py dist
        RUST_CONFIGURE_ARGS: --build=x86_64-pc-windows-gnu --enable-full-tools --enable-profiler
        CUSTOM_MINGW: 1
        DIST_REQUIRE_ALL_TOOLS: 1